### ISSUE TITLE
How to get tcb_version as required by export_cert_chain_vcek?

### ISSUE THREAD

**Issue by cowbon** [AMDESE/sev-tool#58]
Hi there,
I'm trying to figure out how to get the required `tcb_version` for `export_cert_chain_vcek`. I understand it can be obtained via `SNPPlatformStatus`, but how do I make this `ioctl` call? `psp-sev.h` included in this repo doesn't have such command in the enum or the required formatting `struct`. While I can add this by myself, I'd expect the mapping of each command in the `enum` would match what's documented in ABI specification. However I don't  find `SEV_GET_ID2 ` in such documentation even if it's listed in the enum.

**Comment by larrydewey** [comment]
Hi @cowbon ,

That is a great question. the enum described in `psp-sev.h` has not been updated yet, as the upstream kernel patches have not been finished on the host side. Once those have been finalized, and the work is merged up-stream, I will go in and update the enum values. The current implementation in the [sev-snp-part2](https://github.com/AMDESE/linux/blob/sev-snp-part2-v6/include/uapi/linux/psp-sev.h) is using `0x9` on the host side. The other option is to have the guest owner request an attestation report, and the TCB content may be retrieved from it. The guest owner patches are slotted to be in kernel 5.19, I believe. You can find information on those ioctl calls in the [sev-guest.h](https://git.kernel.org/pub/scm/linux/kernel/git/tip/tip.git/tree/include/uapi/linux/sev-guest.h) of the Linux tip branch.

**Comment by larrydewey** [comment]
With #61 and #56 the SNP enumerations have been updated, but as is mentioned in the comments of `psp-api.h`, these enumerations are subject to changes made in the upstream kernel. If you have additional questions, or if this doesn't fully address your concerns, feel free to re-open this issue or create a new one.

**Comment by larrydewey** [comment]
@cowbon this looks like an issue with passing a `std::string` to sprintf, which can cause some weird behavior. Would you mind trying out 827a235, and seeing if you still have the same issue?

**Comment by cowbon** [comment]
Unfortunately I'm still getting the same error. Is there a format of the URL so I can fill out the parameters manually?

**Comment by larrydewey** [comment]
@cowbon Of course! The URL being generated should look like this: 

```
https://kdsintf.amd.com/vcek/v1/{product_name}/{hwid}?{tcb_parameter_list}

# An Example from a machine I tested 827a235 on: 
https://kdsintf.amd.com/vcek/v1/Milan/7d9c0b5b7511ca54914cb4095d000bcac31e574c06acf214ab827ce7096b4b15431c53dafb67ad4759f66df64a5c775b9be6e69e23ab5df82a69ebae64b41121?blSPL=02&teeSPL=00&snpSPL=06&ucodeSPL=39
```

For more detailed information, you can refer to the [Versioned Chip Endorsement Key (VCEK) Certificate and KDS Interface Specification](https://www.amd.com/system/files/TechDocs/57230.pdf#page=15). The format should be:

**Comment by cowbon** [comment]
> @cowbon Of course! The URL being generated should look like this:
> 
> ```
> https://kdsintf.amd.com/vcek/v1/{product_name}/{hwid}?{tcb_parameter_list}
> 
> # An Example from a machine I tested 827a235 on: 
> https://kdsintf.amd.com/vcek/v1/Milan/7d9c0b5b7511ca54914cb4095d000bcac31e574c06acf214ab827ce7096b4b15431c53dafb67ad4759f66df64a5c775b9be6e69e23ab5df82a69ebae64b41121?blSPL=02&teeSPL=00&snpSPL=06&ucodeSPL=39
> ```
> 
> For more detailed information, you can refer to the [Versioned Chip Endorsement Key (VCEK) Certificate and KDS Interface Specification](https://www.amd.com/system/files/TechDocs/57230.pdf#page=15).

It turns out the parameters I retrieved were beyond the permitted range. I got `blSPL` = 240, `teeSPL` = 183, `snpSPL` = 00, `ucodeSPL` = 00 but the allowed maximum of `blSPL`, `teeSPL` and `snpSPL` is 127

**Comment by larrydewey** [comment]
@cowbon Can you confirm what version of FW you are running? With the above patches, `sev-tool` is expecting the host to be running FW version 1.51. If you are getting invalid values, it leads me to believe there is a version mismatch happening.

**Comment by cowbon** [comment]
> @cowbon Can you confirm what version of FW you are running? With the above patches, `sev-tool` is expecting the host to be running FW version 1.51. If you are getting invalid values, it leads me to believe there is a version mismatch happening.

Hi @larrydewey , is there a quick way to check the FW version in CLI, such as `sev-tool` or `dmesg`, thanks

**Comment by larrydewey** [comment]
@cowbon you can find the FW version using `dmesg` and grepping for the ccp version. It should look something like this:

```zsh
$ dmesg | grep ccp
...
[   14.686253] ccp 0000:26:00.1: SEV-SNP API:1.51 build:3
...
```

**Comment by cowbon** [comment]
```[root@mymachine ~]# dmesg | grep ccp
[   23.854155] ccp 0000:22:00.1: enabling device (0140 -> 0142)
[   23.866032] ccp 0000:22:00.1: no command queues available
[   23.879098] ccp 0000:22:00.1: sev enabled
[   23.891581] ccp 0000:22:00.1: psp enabled
[   23.905090] ccp 0000:a2:00.1: enabling device (0140 -> 0142)
[   23.918645] ccp 0000:a2:00.1: no command queues available
[   24.008729] ccp 0000:22:00.1: SEV firmware update successful
[   24.090501] ccp 0000:22:00.1: SEV API:1.42 build:42
```
Unfortunately I don't have this in `dmesg`. It seems the FW is missing

**Comment by larrydewey** [comment]
@cowbon it is on the last line of your output:
```zsh
[   24.090501] ccp 0000:22:00.1: SEV API:1.42 build:42
```

It looks like you are running an outdate version of the firmware. Upgrading to FW version 1.51 should fix this issue for you.

**Comment by cowbon** [comment]
Now I have FW 1.52, here is my `dmesg | grep -i SEV`
```
[    8.784205] SEV-SNP: RMP table physical address 0x0000007fcf500000 - 0x000000804fafffff
[   21.651486] ccp 0000:22:00.1: sev enabled
[   29.427966] ccp 0000:22:00.1: SEV-SNP API:1.52 build:4
[   29.479195] SEV supported: 10 ASIDs
[   29.483081] SEV-ES and SEV-SNP supported: 499 ASIDs
[  501.410336] SEV_GET_ID command is deprecated, use SEV_GET_ID2
```
But I still get the following URL with `sev-tool`. The parameters are still beyond 127
```
# ./sevtool --ofolder certs --export_cert_chain_vcek
--2022-07-14 14:10:11--  https://kdsintf.amd.com/vcek/v1/Milan/c2a6528b7364e07e9f5c653ab3aa0dbd7384f9a80dfde54cc643ddbb89d8936425ff8a32568ca6ed771020dc39c33ccffb3b43cac0c501a0093cad6012dfd3ed?blSPL=161&teeSPL=140&snpSPL=00&ucodeSPL=00
```

**Comment by larrydewey** [comment]
@cowbon this behavior sounds suspiciously like a known bug in the existing firmware. Next step I would recommend is manually re-loading the CCP driver:

```zsh
# Manually unload the KVM_AMD kernel driver.
sudo modprobe -r kvm_amd

# Confirm there is no CCP driver still running
lsmod | grep ccp

# Manually re-load the KVM_AMD kernel driver
# (which subsequently re-loads the CCP driver).
sudo modprobe kvm_amd
```

**Comment by cowbon** [comment]
> @cowbon this behavior sounds suspiciously like a known bug in the existing firmware. Next step I would recommend is manually re-loading the CCP driver:
> 
> ```shell
> # Manually unload the KVM_AMD kernel driver.
> sudo modprobe -r kvm_amd
> 
> # Confirm there is no CCP driver still running
> lsmod | grep ccp
> 
> # Manually re-load the KVM_AMD kernel driver
> # (which subsequently re-loads the CCP driver).
> sudo modprobe kvm_amd
> ```

This helped. Thanks!
